# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: domain_inspector 0.4.20200303 ruby lib

Gem::Specification.new do |s|
  s.name = "domain_inspector".freeze
  s.version = "0.4.20200303"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Scott Tadman".freeze, "Ayush Newatia".freeze]
  s.date = "2020-08-01"
  s.description = "A library to extract information and subdomains from top-level domains and registered name from generic and international domain names".freeze
  s.email = "ayush@hey.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "data/effective_tld_names.dat",
    "domain_inspector.gemspec",
    "lib/domain_inspector.rb",
    "lib/domain_inspector/tree.rb",
    "test/helper.rb",
    "test/sample/README",
    "test/sample/test.txt",
    "test/test_domain_prefix.rb"
  ]
  s.homepage = "http://github.com/ayushn21/domain_inspector".freeze
  s.rubygems_version = "3.0.3".freeze
  s.summary = "Domain Name Inspection Library".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<simpleidn>.freeze, [">= 0.0.5"])
      s.add_runtime_dependency(%q<json>.freeze, [">= 0"])
      s.add_development_dependency(%q<test-unit>.freeze, [">= 0"])
      s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
    else
      s.add_dependency(%q<simpleidn>.freeze, [">= 0.0.5"])
      s.add_dependency(%q<json>.freeze, [">= 0"])
      s.add_dependency(%q<test-unit>.freeze, [">= 0"])
      s.add_dependency(%q<juwelier>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<simpleidn>.freeze, [">= 0.0.5"])
    s.add_dependency(%q<json>.freeze, [">= 0"])
    s.add_dependency(%q<test-unit>.freeze, [">= 0"])
    s.add_dependency(%q<juwelier>.freeze, [">= 0"])
  end
end

